system:
  variables:
    ENV_RELATIONSHIPS: "PLATFORM_RELATIONSHIPS"
    ENV_ROUTES: "PLATFORM_ROUTES"
    ENV_VARIABLES: "PLATFORM_VARIABLES"
    ENV_APPLICATION: "PLATFORM_APPLICATION"
    ENV_ENVIRONMENT: "PLATFORM_ENVIRONMENT"

stage:
  deploy:
    CRON_CONSUMERS_RUNNER:
      cron_run: true
      max_messages: 250
    CACHE_CONFIGURATION:
      _merge: true
      frontend:
        default:
          backend_options:
            database: 0
            read_timeout: 10
            connect_retries: 3
        page_cache:
          backend_options:
            database: 1
            read_timeout: 10
            connect_retries: 3
    SESSION_CONFIGURATION:
      _merge: true
      redis:
        timeout: 5
        database: 2
        break_after_frontend: 12
        break_after_adminhtml: 30
        first_lifetime: 600
        bot_first_lifetime: 60
        bot_lifetime: 7200
        disable_locking: 0
        min_lifetime: 60
        max_lifetime: 2592000
  post-deploy:
    WARM_UP_PAGES:
      - "cms-page:home:*"
  global:
    SKIP_HTML_MINIFICATION: true
    SCD_ON_DEMAND: true
    SCD_NO_PARENT: true
    SKIP_SCD: true
    SCD_STRATEGY: compact
    X_FRAME_CONFIGURATION: SAMEORIGIN
